### ISSUE TITLE
Create a CONTRIBUTING.MD file

### ISSUE THREAD

**Issue by ciaokitty** [andersonjoseph/shotbit#4]
Hi I am a beginner at contributing to open source and if you'd like I can add a CONTRIBUTING.MD file.

**Comment by andersonjoseph** [comment]
Thank you for offering to contribute! 

Feel free to go ahead and make a PR. I'll glad to review it

**Comment by ciaokitty** [comment]
hi @andersonjoseph i've made a PR.

**Comment by andersonjoseph** [comment]
> hi @andersonjoseph i've made a PR.

hey! I've requested a couple of changes before merging, thanks!

**Comment by ciaokitty** [comment]
> > hi @andersonjoseph i've made a PR.
> 
> hey! I've requested a couple of changes before merging, thanks!

great, i'll work on those! where can i view the changes though? i can't find any related comments on my dashboard

**Comment by andersonjoseph** [comment]
You can see them in the submitted [PR ](https://github.com/andersonjoseph/shotbit/pull/5)

I just pinged you in one of those

**Comment by ciaokitty** [comment]
> You can see them in the submitted [PR ](https://github.com/andersonjoseph/shotbit/pull/5)
> 
> I just pinged you in one of those

hey sorry for the trouble but it'll be helpful for me if you could list the desired changes here once.

**Comment by andersonjoseph** [comment]
> > You can see them in the submitted [PR ](https://github.com/andersonjoseph/shotbit/pull/5)
> > I just pinged you in one of those
> 
> hey sorry for the trouble but it'll be helpful for me if you could list the desired changes here once.

Sure! Here's a screenshot with the changes:

![image](https://github.com/andersonjoseph/shotbit/assets/22438127/fa5c757a-381a-4f95-a93e-2da0df4dca16)

https://github.com/andersonjoseph/shotbit/pull/5/files/7f0dc25084ac42aea19f453be8738601af077296

**Comment by ciaokitty** [comment]
@andersonjoseph sorry for the immense delay on this small issue but i finally pushed the required changes, also let me know if you need help with anything else!

**Comment by andersonjoseph** [comment]
closed in: #5 

thank you! 🙌
